!----------------------------------------------------------------------
! PARAMESH - an adaptive mesh library.
! Copyright (C) 2003
!
! Use of the PARAMESH software is governed by the terms of the
! usage agreement which can be found in the file
! 'PARAMESH_USERS_AGREEMENT' in the main paramesh directory.
!----------------------------------------------------------------------

!
! These are wrapper routines for some mpi calls. We need these to avoid an error
! message generated by the NAG F95 compiler, when the mpi routines are called for
! different datatypes within the same calling routine.
!


! Reduction operations


       subroutine mpi_dble_allreduce(sendbuf,recvbuf,count,datatype, & 
     &                               op,comm,ierror)
       double precision    :: sendbuf(*),recvbuf(*)
       integer             :: count,datatype,op,comm,ierror

       call mpi_allreduce(sendbuf,recvbuf,count,datatype, & 
     &                    op,comm,ierror)

       return
       end subroutine mpi_dble_allreduce


